project_id: your-project-id
region: europe-west3
domain: member
table: users
raw_dataset: member_raw
structure_dataset: member_structure
reconciler:
  aws_bucket: your-aws-bucket
  aws_prefix: path/to/member/raw/
dq:
  not_null: ["record_id"]