# member-pipeline/config/pipeline_config.yaml
pipeline:
  name: "member-cdc-pipeline-v2"
  streaming: true

# Storage Write API Configuration
bigquery:
  write_method: "STORAGE_WRITE_API"
  storage_write_config:
    num_streams: 50
    triggering_frequency_sec: 60
    exactly_once: true
    auto_sharding: true

# Window Configuration
windows:
  notification:
    duration_sec: 1
    allowed_lateness_sec: 10
  raw:
    duration_sec: 60
    allowed_lateness_min: 5
    early_firing_sec: 30
  structure:
    duration_sec: 60
    allowed_lateness_min: 5
  refined:
    duration_sec: 300
    allowed_lateness_min: 10
    early_firing_min: 2
  analytics:
    duration_sec: 300
    allowed_lateness_min: 10

# Performance Tuning
performance:
  num_workers: 10
  max_num_workers: 50
  machine_type: "n2-highmem-8"
  disk_size_gb: 100
  enable_streaming_engine: true

# S3 Reconciliation
s3:
  bucket: "your-s3-bucket"
  region: "ap-southeast-1"
  base_prefix: "eagleeye/member"
  alert_on_mismatch: true

# Monitoring
monitoring:
  metrics_interval_sec: 60
  enable_profiling: true
