project_id: your-project-id
region: asia-southeast1
domain: member
table: users
id_column: record_id
raw_dataset: member_raw
structure_dataset: member_structure
refined_dataset: member_refined
analytics_dataset: member_analytics
framework_dataset: member_framework

reconciler:
  aws_bucket: your-aws-bucket
  aws_prefix_raw: "eagleeye/member/raw/"
  aws_prefix_structure: "eagleeye/member/structure/"
  aws_prefix_refined: "eagleeye/member/refined/"
  aws_prefix_analytics: "eagleeye/member/analytics/"
  mapping_schemas:
    users:
      user_id:  record_id
      user_name: name
      user_email: email

dq:
  not_null: ["record_id", "email"]